namespace ServerTCP.Gaming.Enums
{
    public enum AbilityType
    {
        None = 0,
        Summon = 8,
        Destroy = 9,
        Draw = 12,
        Freeze = 19,
        Heal = 21,
        Damage = 22,
        DestroyStatus = 25,
        AddStatus = 26,
        RemoveStatus = 27,
        RemoveAbility = 29,
        MultiplyHp = 30,
        AddAttack = 42,
        AddHp = 44,
        RemoveStealth = 57,
        RemoveTaunt = 59,
        RemoveReconstructed = 71,
        Attack = 72,
        AttackHero = 73,
        Initialize = 74,
        RemoveBarriage = 75,
        AddHpAndAttack = 76,
        Sticky = 77,
        RemoveEnraged = 78,
        AddEnraged = 79,
        Chain = 80,
        Blast = 81,
        AddGold = 82,
        BattlecryActivate = 83,
        Avenge = 84,
        Triplet = 85,
        AttackTemp = 86,
        AddAbility = 87,
        Mirage = 88,
    }
}