namespace ServerTCP.Gaming.Enums
{
    public enum AbilityFilterTarget
    {
        None = 0,
        AllByStatusFilterShell = 1,
        AllCardsHandFilter = 2,
        AllMyBoardMinioFilter = 3,
        BattleCryRandomMinionsFilter1 = 4,
        CardOppositeSideFilter = 5,
        EmptyFilter = 6,
        EmptyFilterWithoutCaster = 7,
        FieldMedicFilter = 8,
        GetCardsByCasterType = 9,
        GetCardsByCasterTypeWithAmountType = 10,
        HighCommanderSummonSet = 11,
        IdsTargetsFilter = 12,
        IdTargetFilter = 13,
        RandomCardFilter = 14,
        RandomCardsFilter1 = 15,
        RandomCardsFilter2 = 16,
        RandomCardsFilter4 = 17,
        RandomEnemyDeathAbility = 18,
        SelfCardFilterData = 19,
        StickyFilterMechanic = 20,
        StickyTryUseFilter = 21,
        RandomPronusCardsFilter1 = 22,
        RandomPronusCardsFilter2 = 23,
        RandomPronusCardsFilter2WithoutChronoTitan = 24,
        RaceTypeCybernetics = 25,
        RaceTypeGuardians = 26,
        RaceTypeKatari = 27,
        RaceTypeKrox = 28,
        RaceTypeNeutrals = 29,
        RaceTypePronus = 30,
        RaceTypeRoids = 31,
        RaceTypeWanderers = 32,
        RandomCardsFilter3 = 33,
    }
}